### ISSUE TITLE
update .vim

### ISSUE THREAD

**Issue by FireCui** [ZiChenStudio/vimrc#1]
可以上传.vim文件夹，提供vim的版本信息

**Comment by zichenstudio** [comment]
为什么要提供vim的版本信息呢？vim不是向下兼容吗？

**Comment by FireCui** [comment]
![20231210175005](https://github.com/ZiChenStudio/vimrc/assets/90055899/98287248-e78e-4c4c-afa6-382287b99f62)
Invalid arguments for function range(s:indentSpace+1, s:indentSpace * s:indentLine_indentLevel + 1, s:indentSpace)会出现这个报错， 可能与vim版本相关，indentline没有生效，所以想看看你的vim版本信息，.vim文件能cp直接用更好

**Comment by zichenstudio** [comment]
我的vim版本是9.0，大概是这样
> $ vim --version
> VIM - Vi IMproved 9.
同时也安装了Gvim

**Comment by zichenstudio** [comment]
如果你的问题解决了请自行关闭ISSUE

**Comment by FireCui** [comment]
按照你的配置，也升级到了vim9，还是一样的问题，我的vim-X11的版本是7.4，

**Comment by FireCui** [comment]
是否可以上传你本地的.vim文件，我使用meld比对下

**Comment by zichenstudio** [comment]
我将我的.vim文件夹删除，重新使用vim-plug下载，没有出现任何问题，因此，我觉得这不是我的问题，你可能缺少依赖(不确定)，你或许应该向indentline或vim求助。
